Feat 194 Add table and data to enter receipt page
deptofdefense/solo pull request #208
Opened 2020-03-13 17:57 UTC by jhackshaw-dds

Thanks for submitting a pull request! Below are a few things you can do to help us more quickly review your changes.

## Checklist
I have…
- [x] summarized below my changes and noted which issues (if any) this pull request fixes or addresses.
- [x] thoroughly outlined below the steps necessary to test my changes.
- [x] attached screenshots illustrating relevant behavior before and after my changes.
~~[ ] review and update SSAG documentation if needed.~~

## Summary of Changes
This pull request…
- closes #193 
- closes #194 
- generalize useDocuments hook from status page to a more generic useDocumentApi hook
- add SdnInputForm to enter receipts page
- add table to enter receipts page
- load sdn data asynchronously on form submission
- add loading icon to indicate success/failure of data loading

## Testing
To verify the changes proposed in this pull request…
1. Run unit tests
2. View d6t page in development environment

## Screenshots
<img width="1662" alt="Screen Shot 2020-03-13 at 1 55 05 PM" src="https://user-images.githubusercontent.com/59582489/76647071-7988cc80-6532-11ea-928d-1318250fbb74.png">
<img width="1654" alt="Screen Shot 2020-03-13 at 1 55 35 PM" src="https://user-images.githubusercontent.com/59582489/76647079-7c83bd00-6532-11ea-9037-10b28b7206ce.png">
<img width="1643" alt="Screen Shot 2020-03-13 at 1 56 06 PM" src="https://user-images.githubusercontent.com/59582489/76647088-7ee61700-6532-11ea-956c-0f6bee49d10c.png">
<img width="1655" alt="Screen Shot 2020-03-13 at 1 56 19 PM" src="https://user-images.githubusercontent.com/59582489/76647092-81487100-6532-11ea-8555-a5c25f4f2fe6.png">

2020-03-13 20:08 UTC, SCasarottoDDS requested changes

2020-03-13 20:08 UTC, SCasarottoDDS commented on frontend/src/components/SdnInputForm/SdnInputForm.tsx
> +  );
So this implies that you always want to reset. Success or fail. Do we want to? I lean toward no. People are typing in some long weird thing. It's easy to get wrong and retyping would be frustrating. I would require that the onSubmit be a function that returns a promise so that on success you can clear but on error you done.

2020-03-13 20:08 UTC, SCasarottoDDS commented on frontend/src/hooks/useDocumentApi.ts
> +  }));
Seems like a lot of this object could just be spread. Why not only shape the things that need to change in shaped?

2020-03-13 20:33 UTC, jhackshaw-dds commented on frontend/src/components/SdnInputForm/SdnInputForm.tsx
> +  );
I was thinking that a user with a list of sdns to get through, they shouldn't have to wait for a round trip to the api to move from 1 to the next. Either is fine - if this is the case I will take the loading state/indicator out of the table altogether.

2020-03-13 20:44 UTC, jhackshaw-dds commented on frontend/src/hooks/useDocumentApi.ts
> +  }));
Updated

2020-03-13 21:29 UTC, SCasarottoDDS requested changes

2020-03-13 21:29 UTC, SCasarottoDDS commented on frontend/src/hooks/useDocumentApi.ts
> +    },
Should this be spread

2020-03-14 01:57 UTC, SCasarottoDDS approved these changes

2020-03-14 01:57 UTC, merged