Initiated CI/CD pipeline via GitHub actions to trigger frontend tests
deptofdefense/solo pull request #29
Opened 2020-01-17 18:48 UTC by dds-hansolo

Created .yml file in solo/.github/workflows called on_pull.yml which will run all unit tests written for the react frontend on each pull request.

Thanks for submitting a pull request! Below are a few things you can do to help us more quickly review your changes.

## Checklist
I have…
- [x] summarized below my changes and noted which issues (if any) this pull request fixes or addresses.
- [x] thoroughly outlined below the steps necessary to test my changes.
~~attached screenshots illustrating relevant behavior before and after my changes.~~

## Summary of Changes
This pull request…
- Created a .yml file to all run frontend tests during every pull request.
## Testing
To verify the changes proposed in this pull request…
1. Create a pull request for the current frontend source code.
## Screenshots
N/A

2020-01-17 20:01 UTC, jordangov commented
Question... do we plan to use GH actions for the final product? If not, why not get a very simple version of the final CI tool running?

2020-01-17 20:02 UTC, jhackshaw-dds requested changes

2020-01-17 20:02 UTC, jhackshaw-dds commented on .github/workflows/on_pull.yml
> +        npm test
Nice it works - can we add `npm run typecheck` as another check? I think it would make the most sense after the linting check.

2020-01-19 20:35 UTC, jordangov commented
On Tuesday let's chat about merging feature branches into other feature branches. It's not that this is bad or wrong, but we need to have an understanding of what it means for development workflow.

2020-01-20 17:24 UTC, closed without merging